name: Bug Report
title: '[Bug] Bug'
description: A bug in the code or elsewhere
labels: bug
assignees: merive
body:

- type: input
  id: bug
  attributes:
    label: Bug
    description: "A complete of what the bug is"
  validations:
    required: true

- type: input
  id: steps
  attributes:
    label: Steps to reproduce
    description: "What had you do to make the bug happen?"
  validations:
    required: false

- type: input
  id: extra
  attributes:
    label: Any extra info
  validations:
    required: false
