name: Request new feature
title: '[Enhancement] Enhancement'
description: A enhancement in project
labels: enhancement
assignees: merive
body:

- type: input
  id: enhancement
  attributes:
    label: Enhancement
    description: "Describe a new enhancement"
  validations:
    required: true

- type: input
  id: extra
  attributes:
    label: Any extra info
  validations:
    required: false
