name: Request improvement
title: '[Improvement] Improvement'
description: A enhancement in project
labels: improvement
assignees: merive
body:

- type: input
  id: improvement
  attributes:
    label: Enhancement
    description: "Describe what to need improve"
  validations:
    required: true

- type: input
  id: extra
  attributes:
    label: Any extra info
  validations:
    required: false
