name: Needs refactoring
title: '[Refactoring] Refactoring'
description: A refactoring of the code or elsewhere
labels: refactoring
assignees: merive
body:

- type: input
  id: refactoring
  attributes:
    label: Refactoring
    description: "A complete of what to needs refactoring"
  validations:
    required: true

- type: input
  id: extra
  attributes:
    label: Any extra info
  validations:
    required: false
